package abstractclass;

public enum HazardousMaterialType {
    NOT_HAZARDOUS,
    EXPLOSIVES,
    GASES,
    FLAMMABLE_LIQUID,
    COMBUSTIBLE_LIQUID,
    FLAMMABLE_SOLID,
    SPONTANAEOUSLY_COMBUSTIBLE_AND_DANGEROUS_WHEN_WET,
    OXIDIZER,
    ORGANIC_PEROXIDE,
    POISON_AND_POISON_INHALATION_HAZARD,
    RADIOACTIVE,
    CORROSIVE
}